# -*- coding: utf-8 -*-
"""MajorityVoteClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCtvjS5XxgxoOyMkhGk2bz6H6weYyw2l
"""

import numpy as np
import operator
from pathlib import Path
from sklearn.base import BaseEstimator, ClassifierMixin, clone
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import _name_estimators


class MajorityVoteClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, classifiers, vote='classlabel', weights=None):
        self.classifiers = classifiers
        self.named_classifiers = {
            key: value for key, value in _name_estimators(classifiers)
        }
        self.vote = vote
        self.weights = weights

    def fit(self, X, y):
        # Validate vote parameter
        if self.vote not in ('probability', 'classlabel'):
            raise ValueError(
                f"vote must be 'probability' or 'classlabel'; "
                f"got (vote={self.vote})"
            )

        # Validate weights
        if self.weights is not None and \
                len(self.weights) != len(self.classifiers):
            raise ValueError(
                f'Number of classifiers and weights must be equal; '
                f'got {len(self.weights)} weights, '
                f'{len(self.classifiers)} classifiers'
            )

        # Encode class labels
        self.lablenc_ = LabelEncoder()
        self.lablenc_.fit(y)
        self.classes_ = self.lablenc_.classes_

        # Clone and fit classifiers
        self.classifiers_ = []
        for clf in self.classifiers:
            fitted_clf = clone(clf).fit(
                X,
                self.lablenc_.transform(y)
            )
            self.classifiers_.append(fitted_clf)

        return self

