# -*- coding: utf-8 -*-
"""sentiment_analysis_Imdb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9t86JMPRYJVLNNa6RXQsxXdzv3wIwDI

# **Downloading the Data**

Using the Requets  -- downloading the data through link --> https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
"""

#Downlaoding the Data
import requests

URL = "https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz"

request = requests.get(URL)
with open("data.tar", "wb") as f:
  f.write(request.content)
print("Done")

"""### **Reading the Tar file**

reading the tar file and extracting all the file
"""

import tarfile as t

with t.open('data.tar', 'r:gz') as f:
  f.extractall()

print('data.tar Is extracted , DONE :)')

# 1. preparing the Data
!pip install pyprind
import pyprind
import pandas as pd
import os
import sys

print("Instalation and importing is DONE")

from tqdm.auto import tqdm   ## this is the progress bar
BASEPATH = '/content/aclImdb'
labels = {'pos': 1,
          'neg': 0}

df = pd.DataFrame(columns=['review','sentiments'])
for s in ('test' , 'train'):
  for l in('pos','neg'):
    path = os.path.join(BASEPATH , s ,l)
    for file in tqdm(sorted(os.listdir(path))):
      with open(os.path.join(path, file),'r' , encoding='utf-8') as infile:
        txt = infile.read()
      df.loc[len(df)] = [txt, labels[l]]

# 2. simce the Data is we saperated need to reshuffle
import numpy as np
np.random.seed(0)
df = df.reindex(np.random.permutation(df.index))

df.to_csv("movie_data.csv" , index=False , encoding = 'utf-8')

"""# **Transforming the words into feature Vectors**

Using the `sklearn.feature_extraction.text` and `CountVectorizer`

`CountVectorizer`  --> To construct a bag-of-words based on the words count in the respective documents

What is a **Bag-of-Words**

1. we create a vocabulary of the unique tokens - eg words from the entire dataset
2. We construct a feature vector that contain the count how often the words occur in particular documents
"""

# Tranforming words into feature vectors
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
counts = CountVectorizer()

# Eg. of how it is going to work
docs = np.array(['The Moon is white',
                 'The Waether is sweet',
                 'The moon is white , The weather is sweet',
                 'And one and one is two'])
BAG = counts.fit(docs)

BAG = counts.transform(docs)

# Looking at What model Just model did
print('The counts of the vocab is in form of dictionary \n',counts.vocabulary_)

print('The feature vectors for this dictinary \n', BAG.toarray())

"""### **Assesing Word relevency via TFIDF**

with the `l2 normalization`
`l2` --> L2 regularization, is a technique used in linear regression to prevent overfitting by adding a penalty term to the loss function. This penalty is proportional to the square of the magnitude of the coefficients
"""

from sklearn.feature_extraction.text import TfidfTransformer

# setting the tfidf tranformer
tfidf = TfidfTransformer(use_idf= True,
                         smooth_idf= True,
                         norm = 'l2')
np.set_printoptions(precision=2)  ### This actually set out the output of the numpy array [0.34556] --> [0.34]

print(tfidf.fit_transform(counts.fit_transform(docs)).toarray())

"""### **Cleaning Of the Data**

The previous is the example of the tfidf works now we need it to apply on the model so first we need to remove the unwanted words and start the cleaning process
"""

df.head()

### Checking the random Review

idx = df.sample(1).index[0] # this is for the random ness
print(df.loc[idx,'review'][-100:])
print("The Index of the review is  ",idx)

# 2. The example should look like this
# ften underestimated and forgotten, but very worthy.<br /><br />This should definitely be on Top 250.
# The Index of the review is   (5680)

# Setting the cleaning Function
import re

def text_preprocessor(text):
    text = re.sub(r'<[^>]*>', '', text)

    emoticons = re.findall(
        r'(?::|;|=)(?:-)?(?:\)|\(|D|P)',
        text
    )

    text = (
        re.sub(r'[\W]+', ' ', text.lower())
        + ' '.join(emoticons).replace('-', '')
    )

    return text

# checking for the 1 sample

text = df.loc[5680, 'review'][-100:]

# Testing the pre processor
test = text_preprocessor(text=text)
test

# Applying to whole dataset

df['review'] = df['review'].apply(text_preprocessor)

"""## **Processing Documents into Tokens**

after succesfully cleaning the data from the abnormalities now we need to think how can saperate the text into split individual elemenst

#### *Using the porter.stem method*
`from nltk.stem.porter import PorterStemmer` <-- it is basically an advance version of our function where it can return the text in the base form

this is the oldest stemming algo but there are newre also
* snowBall stemmer
* Lancaster stemmer

*what does the stemming do is*

a text preprocessing technique that reduces words to their canonical dictionary base form (known as a "lemma") based on their intended meaning and part of speech
"""

# 1. Creating the tokenizer function

def tokenizer(text):
  """This function is used to split the text and help tkenize them """
  return text.split()

# 2. Testing the function
tokenizer('This is the testing function and testing is on the data')

#1. using the porterstem method
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()

# 2. creating the function using the Porterstemmer
def stem_tokenizer(text):
  """Using the stemmer NLTK"""
  return [porter.stem(word) for word in text.split()]

# 3. testiing the function
stem_tokenizer('this is the testing function and testing is on the data')

"""## **STOP WORDS REMOVAL**"""

import nltk

nltk.download('stopwords')
print("DOWNLAOD , DONE")

from nltk.corpus import stopwords
stop = stopwords.words('english') # < choosinf the english
[w for w in stem_tokenizer('this is the testing function and testing is on the data') if w not in stop]

"""# **Training the Logistic regression Model For this document classification**

splitting the data In train and test , With Hyper parameters tuning and choosing the best parameteers

1. creating the Dictionary for parameters `small_params_grid`
2. creating the pipeline for `TFIDF` and `LogisticRegression`
3. Creating the model and passing the values in `GridSearchCV`
"""

# 1. splitting the data
### dividing the data equally in 25k for trainng and testing
X_train = df.loc[:25000, 'review'].values
y_train = df.loc[:25000, 'sentiments'].values
X_test = df.loc[25000:, 'review'].values
y_test = df.loc[25000:, 'sentiments'].values

len(X_train), len(X_test), len(y_train), len(y_test)

from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. creating the Tfidf Vectorizer to convert the values into dictionaries
tfidf = TfidfVectorizer(strip_accents= None,
                        lowercase = False,
                        preprocessor = None)

# 2. creating the small_param_grid

small_param_grid = [
    {
        'vect__ngram_range':[(1,1)],
        'vect__stop_words': [None],
        'vect__tokenizer' : [tokenizer , stem_tokenizer],
        'clf__penalty': ['l2'],
        'clf__C' : [1.0 , 10.0]
    },
    {
        'vect__ngram_range':[(1,1)],
        'vect__stop_words': [stop, None],
        'vect__tokenizer' : [tokenizer],
        'vect__use_idf' : [False],
        'vect__norm' : [None],
        'clf__penalty': ['l2'],
        'clf__C' : [1.0 , 10.0]
    }
]

# 3. Creating the pipeline
lr_tfidf = Pipeline([
    ('vect' , tfidf),
    ('clf', LogisticRegression(solver= 'liblinear'))
    ])

# 4. creating instance for the Model
gs_lr_tfidf = GridSearchCV(lr_tfidf , small_param_grid , scoring = 'accuracy' , cv = 5 , verbose = 2, n_jobs=1)

# 5. FITTING THE MODEL
gs_lr_tfidf.fit(X_train , y_train)

print(f"The best Parameter are {gs_lr_tfidf.best_params_}")
print(f"The best scores are {gs_lr_tfidf.best_score_}")

clf = gs_lr_tfidf.best_estimator_
print(f"The Accuracy is {clf.score(X_test , y_test)}")

"""## **SAVING THE PKL**

To save this model we need to import the pkl file
"""

import pickle


# 1. saving the model

with open('Sentiment_model.pkl' , 'wb') as f:
  pickle.dump(clf , f)

"""### Implementing the **KERAS NN** on this"""

from tensorflow import keras

print(keras.__version__)
print("Print is Done")

# splitting the Data Again
from sklearn.model_selection import train_test_split
X = df['review']
y = df['sentiments']

X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 ,stratify = y, random_state = 42)

len(X_train), len(X_test), len(y_train), len(y_test)

# spliting the Data into validation set
X_train , X_val , y_train , y_val = train_test_split(X_train , y_train , test_size = 0.2 ,stratify = y_train, random_state = 42)

len(X_train), len(X_val), len(y_train), len(y_val)

# 1. Checking the X_train and Xtest data
print(f"This is X_train : {X_train[0]}")

# 2. Coverting this raw text to the Vector to feed in the  Nn

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_nn = TfidfVectorizer(stop_words = stop,
                           ngram_range= (1,1),
                           max_features = 5000,
                           tokenizer = stem_tokenizer)

print("Done")

# 3. passing the Data
import time
from tqdm import tqdm
pbar = tqdm(total=100)
X_TRAIN = tfidf_nn.fit_transform(X_train)
time.sleep(1)
pbar.update(33)
X_VAL = tfidf_nn.transform(X_val)
time.sleep(1)
pbar.update(66)
X_TEST = tfidf_nn.transform(X_test)
time.sleep(1)
pbar.update(100)
pbar.close()

print(X_TRAIN.shape)
print(X_VAL.shape)
print(X_TEST.shape)

# coverting the sparse tfidf to dense array
X_train_dense = X_TRAIN.toarray()
X_test_dense = X_TEST.toarray()
X_val_dense = X_VAL.toarray()

print(type(X_TRAIN))
print(type(X_train_dense))

"""## **Creating the Keras NN**

from importing the Sequential creating the NN
"""

from keras import Sequential
from keras.layers import Dense , Dropout


# 1. Buildind the NN
model = Sequential([
    Dense(128 , activation = 'relu' , input_shape=(5000,)),
    Dropout(0.5),
    Dense(64 , activation = 'relu'),
    Dropout(0.5),
    Dense(1 , activation = 'sigmoid')
])

model.summary()

# Model are so accessible we can get the weight and bias of the models
hidden1 = model.layers[0]
weight , bias  = hidden1.get_weights()

weight, bias # theses are the weight and bias of the model

### Compilong the model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.summary()

# training the  model

history = model.fit(X_train_dense,
                    y_train,
                    validation_data = (X_val_dense , y_val),
                    epochs = 5,
                    batch_size = 32
                    )

# Evaluating the mmodel
loss , acc = model.evaluate(X_test_dense , y_test)

print(f"Test Loss is {loss}")
print(f"Test Accuracy is {acc}")

history.history.keys()

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], label='train')
plt.plot(history.history['val_accuracy'], label='validation')
plt.legend()
plt.show()

plt.plot(history.history['loss'], label='train')
plt.plot(history.history['val_loss'], label='validation')
plt.legend()
plt.show()