# -*- coding: utf-8 -*-
"""password_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUJbmQJC12200gfSdmgqsVFdYoYOEAAo
"""

print("This is the password checker")
print("="*50)
print("You have only three Attempts")

attempts = 3
password = "SUSHANT"

while attempts > 0:
  guess = input("Enter the Pasword : ")

  if guess == password:
    print("="*50)
    print("Successful Attempt, UNLOCKED")
    break
  else:
    attempts -= 1
    print("Try Again")

    if attempts > 0:
      print("Attempts Left", attempts)
if attempts == 0:
  print("Access Denied")

