# -*- coding: utf-8 -*-
"""Shopping_bill.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Piwp3_ac9gHpIKgaz9dOq3WgrXONRRWo
"""

print("Welcome to shoping bill Calculator")

item_1 = input("Enter Item 1 :" )
price_1 = float(input("Enter price : "))

item_2 = input("Enter Item 2 : ")
price_2 = float(input("Enter price : "))

item_3 = input("Enter Item 3 : ")
price_3 = float(input("Enter price : "))

total = price_1+price_2+price_3
print()

print("------------Bill-------------")
print(item_1,":", price_1)
print(item_2,":", price_2)
print(item_3,":", price_3)
print("-----------------------------")
print(f"Total : {total:.3f}")



# Applying the Discount
print("="*30)
print("Applying discount")

if 499 <= total <= 999:
    total = total * 0.9
    print("10% discount applied!")
elif total > 999:
    total = total * 0.8
    print("20% discount applied!")
else:
    print("No discount")

print("------------------------")
print("After Discount")
print(f"Total : {total:.2f}")

# Applying the Discount
print("="*30)
print("Applying discount")

if total in range(499 , 999):
  total = (total * 0.9)
elif total > 999:
  total = (total * 0.8)
else:
  print("no discount")

print("------------------------")
print("After Discount")
print("Total : ", total)

